### ISSUE TITLE
What does EN_Equivalent signify?

### ISSUE THREAD

**Issue by insanity54** [Akenaide/wsoffdata#1]
I see a lot of `"EN_Equivalent": false`, however I don't see any `"EN_Equivalent": true`. 

What does the `EN_Equivalent` boolean signify? Is it meant to be toggled on for english edition card data? I don't see any english card data so EN_Equivalent got me curious.

**Comment by Akenaide** [comment]
Yeah I guess it meant to know if EN format has this card or not. This repo was meant to provide cards information for the simulator and they need this in the JSON. 

I have this information as a placeholder, so don't trust it.

**Comment by insanity54** [comment]
Makes sense, thanks!
